[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
pixels = "0.13.0"
rand = "0.8.5"
winit = { version = "0.30.5", features = ["rwh_05"] }
